---

- name: Silently block all undefined vhost access
  copy: src=default.block dest=/etc/nginx/sites-available/default.block owner=root group=root mode=0644

- name: Enable the default blocking
  file: path=/etc/nginx/sites-enabled/00_default.block
        src=/etc/nginx/sites-available/default.block
        state=link
  notify:
    - restart nginx

